### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/flying-squid#15]
Would simplify deployment and setup

**Comment by rom1504** [comment]
Could be fun.
Not sure if it's really useful though.

**Comment by mhsjlw** [comment]
@rom1504 I mean we will do this when we have *a lot* of time and we've finished our TODO.md or the community has a demand for it

**Comment by rom1504** [comment]
This is fun but really this is polluting the issues, we'll reopen it when it makes sense.

**Comment by rom1504** [comment]
Apparently it's easy, see https://github.com/kstaken/dockerfile-examples/blob/master/nodejs/Dockerfile

**Comment by rom1504** [comment]
https://github.com/mhsjlw/flying-whale/blob/master/Dockerfile

Should this be in a different repo or directly in flying-squid ?

**Comment by mhsjlw** [comment]
Different repo. It is the convention to not have the code in the same repo because the docker registry should just contain the setup not the code itself but the setup needs to grab the code

**Comment by rom1504** [comment]
OK

**Comment by mhsjlw** [comment]
http://github.com/mhsjlw/flying-whale

**Comment by mhsjlw** [comment]
I said a bunch of stuff that didn't make sense: will keep here though

> mhsjlw: No, it should be seperate the container should grab the code
> rom1504: OK

That's not the convention, the Dockerfile should be in the root of this repository. This is now something that should be looked into as it would greatly simplify quickly getting started

**Comment by TheBrenny** [comment]
Bump. I'm trying to build the Dockerfile in the deploy folder, and it just isn't working. I've tried multiple different variations of a Dockerfile, and nothing works. I've even tried using `docker-compose`, but it just grabs the published image, which shouldn't be the case IMO - if I've downloaded the code, I clearly want to modify things, so the local `docker-compose.yaml` shouldn't pull a remote image...

Then there are errors that `npm install` is looking for `node_modules/flying-squid/.....` which makes zero sense, because obviously it's not a dependency to itself...

Additionally, I was also getting errors because npm couldn't find a `package-lock.json`. Found the reason to be in the `npmrc` file and I couldn't find out why...

I'm recreating the Dockerfile (tbh, I don't get why it's breaking - there's not much to change), but maybe it might be worth it to make the readme a bit more verbose on how to build, let alone, rethinking the need for the docker-compose file.

**Comment by TheBrenny** [comment]
> Bump. I'm trying to build the Dockerfile in the deploy folder, and it just isn't working. I've tried multiple different variations of a Dockerfile, and nothing works. I've even tried using `docker-compose`, but it just grabs the published image, which shouldn't be the case IMO - if I've downloaded the code, I clearly want to modify things, so the local `docker-compose.yaml` shouldn't pull a remote image...

I've added to the `README.md` to be a bit more verbose on doing docker tings for a local copy. I also modified the docker-compose file to make sure it builds the local image rather than pulling a remote one.

> Then there are errors that `npm install` is looking for `node_modules/flying-squid/.....` which makes zero sense, because obviously it's not a dependency to itself...

Turns out the error was coming from the `bin` property of the package.json. Fixed this by adding a line to the Dockerfile which makes npm more or less ignore creating bin commands.

> Additionally, I was also getting errors because npm couldn't find a `package-lock.json`. Found the reason to be in the `npmrc` file and I couldn't find out why...

I realise that this statement isn't as expressive as I was thinking - I couldn't find out why we don't want to save the package-lock. I still don't understand why.

> I'm recreating the Dockerfile (tbh, I don't get why it's breaking - there's not much to change), but maybe it might be worth it to make the readme a bit more verbose on how to build, let alone, rethinking the need for the docker-compose file.

Like I said, I've added to the README to make it more obvious for building a local docker image.

PR inbound! 😁

**Comment by Pandapip1** [comment]
@rom1504 this appears to have been implemented at some point and looks like it can be closed.
