### ISSUE TITLE
Banned player writes "undefined disconnected" in chat on connect

### ISSUE THREAD

**Issue by Creeplays** [PrismarineJS/flying-squid#176]

**Comment by demipixel** [comment]
Issue is in login.js

We set `player.username` in `addPlayer()` which is called from `player.login()`. Issue is, we kick them (because they're banned) in `player.login()` before ever getting to `addPlayer()`. Should we just set the username earlier or should we move addPlayer earlier? (Which would give them a lot of properties like health, crouching, etc, which they shouldn't have)

**Comment by rom1504** [comment]
fixed by b39072ebb2f41e9a226c018abe3804c02d2db597
