### ISSUE TITLE
Modernize library

### ISSUE THREAD

**Issue by ethanent** [PrismarineJS/flying-squid#318]
I'm proposing the implementation of a few upgrades:

- Fix crashes and bugs caused by missing server start options in the `createMCServer` method. (ex. not including `player-list-text` options `header` and `footer` prevents players from connecting and crashes, not including `modpe‘ results in world not loading)
- Support `node-minecraft-protocol`'s client protocol autodetection (Support all client versions.)
- Prevent crashing by removing any unhandled `throw`s which could be triggered by clients or at any point except startup.
- Allow removal of command system / default commands.
- Allow customization of world saving / disabling world saving.

Obviously no one's being paid to work on this project, so of course this could take some time! I'd be interested in helping with these upgrades to the project as well.

**Comment by rom1504** [comment]
So first, there's a wip "1.9" PR which brings multiversion and fixes.

There are still some stuff to fix there, but once fixed it will be the new
master.

On your points :
1. I think that's fixed in the pr, to be checked
2. Done in the pr
3. Flying-squid is promise based and should throw. They are caught and
remitted as 'error' event somewhere
4. Already done, see the API doc
5. Already possible

Helping to fix the "1.9" pr would help.

**Comment by ethanent** [comment]
Ok, thanks for the info! I'll give all of this a try.

Do you happen to be able to provide a bit more information about how to disable world saving after loading? @rom1504
